<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="9" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="172900" started-at="2018-05-27T11:51:25Z" finished-at="2018-05-27T11:54:18Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="172900" started-at="2018-05-27T11:51:25Z" finished-at="2018-05-27T11:54:18Z">
      <class name="testcases.Release_2018_01_Test">
        <test-method status="PASS" signature="startReport()[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa]" name="startReport" is-config="true" duration-ms="221" started-at="2018-05-27T17:21:25Z" finished-at="2018-05-27T17:21:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa]" name="beforeClass" is-config="true" duration-ms="8034" started-at="2018-05-27T17:21:25Z" finished-at="2018-05-27T17:21:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="TC001_site_open_positive()[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa]" name="TC001_site_open_positive" duration-ms="25" started-at="2018-05-27T17:21:33Z" finished-at="2018-05-27T17:21:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC001_site_open_positive -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa]" name="getResult" is-config="true" duration-ms="6006" started-at="2018-05-27T17:21:33Z" finished-at="2018-05-27T17:21:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TC001_site_open_positive status=SUCCESS method=Release_2018_01_Test.TC001_site_open_positive()[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="TC002_click_RegisterLink_positive()[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa]" name="TC002_click_RegisterLink_positive" duration-ms="1409" started-at="2018-05-27T17:21:39Z" finished-at="2018-05-27T17:21:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC002_click_RegisterLink_positive -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa]" name="getResult" is-config="true" duration-ms="6001" started-at="2018-05-27T17:21:41Z" finished-at="2018-05-27T17:21:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TC002_click_RegisterLink_positive status=SUCCESS method=Release_2018_01_Test.TC002_click_RegisterLink_positive()[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="TC003_successful_Register()[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa]" name="TC003_successful_Register" duration-ms="26821" started-at="2018-05-27T17:21:47Z" finished-at="2018-05-27T17:22:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC003_successful_Register -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa]" name="getResult" is-config="true" duration-ms="6001" started-at="2018-05-27T17:22:14Z" finished-at="2018-05-27T17:22:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TC003_successful_Register status=SUCCESS method=Release_2018_01_Test.TC003_successful_Register()[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="TC004_click_SignOffLink_positive()[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa]" name="TC004_click_SignOffLink_positive" duration-ms="1660" started-at="2018-05-27T17:22:20Z" finished-at="2018-05-27T17:22:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC004_click_SignOffLink_positive -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa]" name="getResult" is-config="true" duration-ms="6001" started-at="2018-05-27T17:22:21Z" finished-at="2018-05-27T17:22:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TC004_click_SignOffLink_positive status=SUCCESS method=Release_2018_01_Test.TC004_click_SignOffLink_positive()[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="TC005_click_SignOnLink_positive()[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa]" name="TC005_click_SignOnLink_positive" duration-ms="1046" started-at="2018-05-27T17:22:27Z" finished-at="2018-05-27T17:22:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC005_click_SignOnLink_positive -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa]" name="getResult" is-config="true" duration-ms="6001" started-at="2018-05-27T17:22:28Z" finished-at="2018-05-27T17:22:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TC005_click_SignOnLink_positive status=SUCCESS method=Release_2018_01_Test.TC005_click_SignOnLink_positive()[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="TC006_loginValidUsernamePassword()[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa]" name="TC006_loginValidUsernamePassword" duration-ms="14025" started-at="2018-05-27T17:22:34Z" finished-at="2018-05-27T17:22:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC006_loginValidUsernamePassword -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa]" name="getResult" is-config="true" duration-ms="6001" started-at="2018-05-27T17:22:48Z" finished-at="2018-05-27T17:22:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TC006_loginValidUsernamePassword status=SUCCESS method=Release_2018_01_Test.TC006_loginValidUsernamePassword()[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="TC007_CompleteFlightBookingSuccessful()[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa]" name="TC007_CompleteFlightBookingSuccessful" duration-ms="14203" started-at="2018-05-27T17:22:54Z" finished-at="2018-05-27T17:23:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC007_CompleteFlightBookingSuccessful -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa]" name="getResult" is-config="true" duration-ms="6002" started-at="2018-05-27T17:23:09Z" finished-at="2018-05-27T17:23:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TC007_CompleteFlightBookingSuccessful status=SUCCESS method=Release_2018_01_Test.TC007_CompleteFlightBookingSuccessful()[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="TC008_loginInvalidUsername()[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa]" name="TC008_loginInvalidUsername" duration-ms="23867" started-at="2018-05-27T17:23:15Z" finished-at="2018-05-27T17:23:39Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at testcases.Release_2018_01_Test.TC008_loginInvalidUsername(Release_2018_01_Test.java:501)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC008_loginInvalidUsername -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa]" name="getResult" is-config="true" duration-ms="6000" started-at="2018-05-27T17:23:39Z" finished-at="2018-05-27T17:23:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TC008_loginInvalidUsername status=FAILURE method=Release_2018_01_Test.TC008_loginInvalidUsername()[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="TC009_loginInvalidPassword()[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa]" name="TC009_loginInvalidPassword" duration-ms="23197" started-at="2018-05-27T17:23:45Z" finished-at="2018-05-27T17:24:08Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at testcases.Release_2018_01_Test.TC009_loginInvalidPassword(Release_2018_01_Test.java:555)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC009_loginInvalidPassword -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa]" name="getResult" is-config="true" duration-ms="6000" started-at="2018-05-27T17:24:08Z" finished-at="2018-05-27T17:24:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TC009_loginInvalidPassword status=FAILURE method=Release_2018_01_Test.TC009_loginInvalidPassword()[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa]" name="afterClass" is-config="true" duration-ms="2074" started-at="2018-05-27T17:24:14Z" finished-at="2018-05-27T17:24:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="FAIL" signature="endReport()[pri:0, instance:testcases.Release_2018_01_Test@29ee9faa]" name="endReport" is-config="true" duration-ms="0" started-at="2018-05-27T17:24:16Z" finished-at="2018-05-27T17:24:16Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials n18-v6sm64417749pfg.36 - gsmtp
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials n18-v6sm64417749pfg.36 - gsmtp

	at utilities.EmailHelper.sendEmail(EmailHelper.java:111)
	at testcases.Release_2018_01_Test.endReport(Release_2018_01_Test.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.afterRun(TestRunner.java:1021)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials n18-v6sm64417749pfg.36 - gsmtp

	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:950)
	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:861)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:766)
	at javax.mail.Service.connect(Service.java:388)
	at javax.mail.Service.connect(Service.java:246)
	at javax.mail.Service.connect(Service.java:195)
	at javax.mail.Transport.send0(Transport.java:254)
	at javax.mail.Transport.send(Transport.java:124)
	at utilities.EmailHelper.sendEmail(EmailHelper.java:105)
	... 23 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- testcases.Release_2018_01_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
